### ISSUE TITLE
NWERC information page

### ISSUE THREAD

**Issue by simonlindblad** [lithekod/site#10]
We need a way to display information to our members regarding NWERC. This could be a simple article (or something like that main page) at lithekod.se/nwerc.

**Comment by holmgr** [comment]
It would be nice with some content so that i can test the actual view. Do we have any such document of which a can take a look at?

**Comment by simonlindblad** [comment]
No, not yet. You can determine the formatting of the content if you want. I will adapt.

**Comment by holmgr** [comment]
Close with commit 7971227eea93aa0cf8cd4d5927110e990bec5e59
