### ISSUE TITLE
Protocols from board meetings

### ISSUE THREAD

**Issue by drathier** [lithekod/site#15]
There's only 5 protocols on the website. I'm pretty sure there has been at least one meeting since november 2014. According to `§3.2.8` in the statutes, they should be available on the website within two weeks of the meeting.

**Comment by simonlindblad** [comment]
Yes, we will fix that. However, not between november 2014 and july 2015 (the time when you were chairman).

**Comment by drathier** [comment]
Looks like we didn't have any official meeting in that time period except the stormöte. There are unofficial protocols, but those should not be published on the website.

**Comment by holmgr** [comment]
The protocol from 15-09-26 has been published
