### ISSUE TITLE
There is no link to the gitlab page.

### ISSUE THREAD

**Issue by david-bergstrom** [lithekod/site#2]
The previous page had a link to http://git.lithekod.se which was used to access the gitlab service we provide for our members. There should be a link somewhere on the page in order to make it findable.

**Comment by holmgr** [comment]
That is a really good question, should we still provide that kind of system or should we encourage usage of Github instead, more specifically, under this organisation?

**Comment by simonlindblad** [comment]
It depends on the usage of private repos at http://git.lithekod.se. I can imagine that participants in Game Jams frequently used them.

**Comment by david-bergstrom** [comment]
There are primarly two usages of the repositories: Game Jams and private use.

The Game Jam and other hackathon usages might be satisfied by writing the link on notes and handing them out, or with some similiar approach.

The question then becomes: Should we promote the git repositiories for private use or are there other sufficient alternatives for the members? The main selling point of our repository it that other solutions has some sort of artificial limit, such as the number of people that can write to the repository (Bitbucket) or that the project has to be public (Github).

**Comment by holmgr** [comment]
That is somewhat my point. Shouldn't we as an organisation strive to promote open source in general? And also being on two seperate platforms (Gitlab and Github) might seem odd or even confusing to which we "recommend"?

**Comment by holmgr** [comment]
Seeing that nobody want to press this issue, i'm closing it.

**Comment by simonlindblad** [comment]
Reopen this. Not everyone is comfortable with having their code open source, neither does all projects benefit from it. I believe that closing an unresolved issue after two days is premature at this stage.

**Comment by dentarg** [comment]
Can't you get private repos from GitHub? See https://education.github.com/

I don't think maintaing your own GitLab instance is worth it if you can get away with GitHub.

**Comment by holmgr** [comment]
Have we had any requests from members to use our GitLab? Is http://git.lithekod.se being used at the GameJams? As @dentarg says, I don't think running our own instance of GitLab is worth it, since there is many third-party platforms such as Github but also the IDA GitLab. Although maybe not everyone at GameJams studies at LiU?
