### ISSUE TITLE
Add people to slack chat

### ISSUE THREAD

**Issue by simonlindblad** [lithekod/site#5]
Since we mention the slack chat on the site, we should also enable users to join it. I don't know of any way to create an "open group", but we could have a form or something similiar to enable users to send a request.

**Comment by holmgr** [comment]
Essentially there is two choices: either we implement a form and some member need to check and invite them manually, or we open up the slack group so that anyone with an student mail can join. The later option means that we simply provide a link to the sign up page. Which should we implement?

**Comment by simonlindblad** [comment]
Even though providing a link to the sign up page would the neater alternative, I would prefer to have a form on the site. Limiting members by using the LiU mail is unnecessary.

**Comment by holmgr** [comment]
Then we would have to manually add them to the slack group, what type of request would we want to implement? Maybe we could integrate with the Slack APIs directly and let a bot inform us when someone wants to signup, or should we just sent an email?

**Comment by simonlindblad** [comment]
It would be nice to have the bot post in some channel (LiTHe-web for example).

**Comment by dentarg** [comment]
This is what you need: https://github.com/rauchg/slackin

**Comment by holmgr** [comment]
Thank you @dentarg , will take a look and test it out.

**Comment by holmgr** [comment]
This feature will be implemented during the next redesign, probably during this summer.

**Comment by simonlindblad** [comment]
Awesome @holmgr
