### ISSUE TITLE
"Mystery meat navigation"

### ISSUE THREAD

**Issue by dentarg** [lithekod/site#6]
I think the menu at http://www.lithekod.se/ need some work :-)

From https://en.wikipedia.org/wiki/Mystery_meat_navigation

> Mystery meat navigation (also known as MMN) is a disparaging term coined in 1998 by Vincent Flanders, author and designer of the website Web Pages That Suck, to describe a web page where the destination of the link is not visible until the user points their cursor at it.[1] Such interfaces lack a user-centered design, emphasizing aesthetic appearance, white space, and the concealment of relevant information over basic practicality and functionality.

![image](https://cloud.githubusercontent.com/assets/42626/9588365/1c64f836-5028-11e5-8d7e-091143b92e9b.png)

**Comment by holmgr** [comment]
Although I agree that it may need some minor tweaks, the dot style navigation does in my option not qualify as a MMN. Several highly regarded projects (for instance one winner at AWWWARDS http://creativecruise.nl/) use a similar type of navigation. One solution maybe to show the link text when first entering the site?

**Comment by dentarg** [comment]
> the dot style navigation does in my option not qualify as a MMN

"Mystery meat navigation is a term ... to describe a web page where the destination of the link is not visible until the user points their cursor at it."

I don't know what to say, I think it's spot on :-)

> Several highly regarded projects use a similar type of navigation

Just because something is well used doesn't mean it has to be good, here's another example: http://deep.design/the-hamburger-menu/ (actual that's where I picked up the term "mystery meat navigation", I didn't know there was a name for it before I read it)

**Comment by dentarg** [comment]
> One solution maybe to show the link text when first entering the site?

I don't think it's enough, and maybe it could be annoying, you see something, but then it goes away... and you can't get it back?

Here's an idea (not very good though): a small text label under each dot

**Comment by holmgr** [comment]
If you hover over the dots a label is shown, the idea that I had (which was expressed poorly above) is to show these by means of the y-position of the viewport. If the hero image is in view (detail work on balancing this) then the labels should be shown. As the user scrolls past a certain point the link text becomes hidden unless the user hovers. This way the user is informed about the navigation, as well as keeping the menu from obstructing the content to a minimum.

**Comment by holmgr** [comment]
Will be closing this issue now as no one else has had any similar comments. However I will take your comments in consideration the next time the site gets redesigned, which probably is sometime this summer.
