### ISSUE TITLE
Link to calendar

### ISSUE THREAD

**Issue by Sjbrgsn** [lithekod/site#8]
We need a link to the event calendar.
https://www.google.com/calendar/ical/lithekod.se_fa4msgl7qpmsdns5oc4fq48ago%40group.calendar.google.com/public/basic.ics

**Comment by david-bergstrom** [comment]
We have received additional complaints about this on Facebook. Anybody got some ideas? :smile:

**Comment by holmgr** [comment]
I have an idea for a solution. Will be trying to implement it tomorrrow during the spotify event.

**Comment by simonlindblad** [comment]
Should there be some text explaining that you can copy the link and paste it into your favorite calendar-program?

**Comment by holmgr** [comment]
The solution should probably bd extended with the actual link to be more compatable with other systems such as Exchange extra. Will start ön that work this evening

**Comment by simonlindblad** [comment]
You are an angel.

**Comment by holmgr** [comment]
It's fixed now
